player32611:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    region: cn-beijing
    access-key-id: LTAI5t7Q15FkJ676QshDEs9G
    access-key-secret: YiWN2BgyFwFdFoUlUNeeemFYSXoBrA
    bucket-name: take-out-player32611
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxc2d8239866abe07a
    secret: 365c8fd522709b0192499000fc869251