spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/take_out_database
    username: root
    password: hcb326630
  redis:
    host: ${player32611.redis.host}
    port: ${player32611.redis.port}
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
player32611:
  jwt:
    admin-secret-key: player32611_take_out_jwt_secret_key_2026
    admin-ttl: 86400000
    admin-token-name: token
    user-secret-key: player32611_take_out_jwt_secret_key_2026
    user-ttl: 86400000
    user-token-name: authentication
  alioss:
    endpoint: ${player32611.alioss.endpoint}
    access-key-id: ${player32611.alioss.access-key-id}
    access-key-secret: ${player32611.alioss.access-key-secret}
    bucket-name: ${player32611.alioss.bucket-name}
  wechat:
    appid: ${player32611.wechat.appid}
    secret: ${player32611.wechat.secret}